### PR TITLE
Copy udunits2.lib too

### PR DESCRIPTION
**Pull request by ocefpaf**
Re-rendered and removed some the yum install step from `build.sh`.

### CODE REVIEW

**Comment by ocefpaf** [comment]
When I add features I get a conflicts. Not sure how to fix that.

```
BUILD END: udunits2-2.2.20-vc9_1
TEST START: udunits2-2.2.20-vc9_1 
Fetching package metadata: ........ 
Solving package specifications: .... 
Error: The following specifications were found to be in conflict:
  - udunits2 2.2.20 vc9_1
Use "conda info <package>" to see the dependencies for each package. 
```

@msarahan can you stop any obvious mistakes I am making here?

**Comment by msarahan** [comment]
Since expat is the only other dependency here, that's probably the problem.  Either expat or one of its dependencies are not available with the vc9 feature.  Are you using the conda-forge recipe?  I assume so, I get no results from ```conda search expat```.  This recipe has no vc features: https://github.com/conda-forge/expat-feedstock/blob/master/recipe/meta.yaml

**Comment by ocefpaf** [comment]
Got it. I need to get all the dependencies to use vc first.  Sorry for the stupid question.

**Comment by msarahan** [comment]
Not a stupid question at all.  This stuff is a mess.  I wish the error messages were more clear.  I think they might be with conda 4.0.

**Comment by ocefpaf** [comment]
> Not a stupid question at all. This stuff is a mess. I wish the error messages were more clear. I think they might be with conda 4.0.

Now that I recall I had the same issue with `expat` :wink: (before i tried the new version [here](https://github.com/conda-forge/expat-feedstock/pull/4)). Expat depends on `msinttypes` and I guess I should add features to `msinttypes` too. However, it seems an overkill to use feature to a package that just drops some header files in the path.

**Comment by msarahan** [comment]
I totally agree.  I'll ask @mcg1969 whether there are any good approaches we can take to break the feature requirement where it makes sense (like with header-only libraries).

**Comment by ocefpaf** [comment]
> I totally agree. I'll ask @mcg1969 whether there are any good approaches
we can take to break the feature requirement where it makes sense (like
with header-only libraries).

Bare in mind that msinttypes is a rare case. Maybe it is not worth fixing
that. (I also believe that we no longer need msinttypes with the latest
Visual Studio.)

**Comment by msarahan** [comment]
Header-only libraries are not terribly common, but they're also not rare.  I think we do need to know how to handle features where packages without features are dependencies.

**Comment by ocefpaf** [comment]
Adding

```yaml
test:
    requires:
        - python {{ environ['PY_VER'] + '*' }}  # [win]
```

solved https://github.com/conda-forge/udunits2-feedstock/pull/4#issuecomment-207576609.

**Pull request merged**
