### PR TITLE
Improve deps

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
I think ideally, we'd create a split package in the mold of [expat](https://github.com/conda-forge/expat-feedstock), with a `libudunits2` package (containing only the shared objects), and a `udunits2` package for development.

**Comment by xylar** [comment]
It looks like there are only about a dozen feedstocks that use `udunits2` right now so it doesn't seem that crazy to make the split.  Presumably, the `udunits2` development package would continue to work for now for all the downstream feedstocks and we would transition them 1 by one to `libudunits2`?

**Comment by zklaus** [comment]
Sounds good. How did you figure out the deps? Can we use a migrator to catch everything?

In any case, I propose to merge this as-is and to implement the split separately.

**Comment by xylar** [comment]
> Sounds good. How did you figure out the deps? Can we use a migrator to catch everything?

Maybe @ocefpaf can tell us if a migrator would be a good idea, or maybe point us to someone else could answer that question.

As far as what feedstocks depend on `udunits2`, I just did a search:
https://github.com/search?q=org%3Aconda-forge+%22-+udunits2%22+path%3A**%2Fmeta.yaml&type=code&ref=advsearch

It looks like we've got 14 feedstocks (besides this one) that have `- udunits2` in their `meta.yaml`.

**Review by xylar — APPROVED** [review]

**Comment by xylar** [comment]
@zklaus, you can either wait if you want more eyes on this or merge now if you like.

**Comment by ocefpaf** [comment]
> Maybe @ocefpaf can tell us if a migrator would be a good idea, or maybe point us to someone else could answer that question.

14 are not that much and if I had to guess, most of those are kind of broken (pynio, etc). I'm not sure a migrator is worth it.

**Comment by xylar** [comment]
@ocefpaf, I agree.  Also, can a migrator be used to change the name of a package?  I'm not aware of any examples of that but I might just not know of them.

**Comment by ocefpaf** [comment]
> Also, can a migrator be used to change the name of a package? I'm not aware of any examples of that but I might just not know of them.

It can run a custom python script to do that but then things start to get more complex and I would do that only if we had +20 feedstocks to modify.

**Comment by zklaus** [comment]
Ok, let's do it manually then. I have started the split in #49.

**Pull request merged**
