### PR TITLE
Updated version to 2.2.26

### PR DESCRIPTION
**Pull request by pelson**
NOTE: I've been unable to build this on my local machine due to https://github.com/conda-forge/m4-feedstock/issues/10. I wonder if it works on the CI's version of OSX...

### CODE REVIEW

**Comment by pelson** [comment]
@conda-forge-bot, please rerender

**Comment by pelson** [comment]
@conda-forge-admin, please rerender

**Comment by pelson** [comment]
Windows issue raised upstream. May have to workaround (use of stdbool.h) depending on the outcome of the linked issue. https://github.com/Unidata/UDUNITS-2/issues/55

**Comment by ocefpaf** [comment]
@pelson I went ahead and merged #17. I recall trying to workaround the `stdbool.h` issue some time ago just to find more vc9 related issues further down the road. I also don't think we'll have upstream support for vc9.

Closing this but please feel free to re-open if you disagree and/or have an idea on how to fix this.

**Pull request closed without merging**
